//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserBackCenter.SMSCenter {
    
    
    public partial class GetExpenseDetails {
        
        /// <summary>
        /// GetExpenseDetail_repExpenseDetail 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ControlLibrary.CustomRepeater GetExpenseDetail_repExpenseDetail;
        
        /// <summary>
        /// GetExpenseDetail_tbSumCountAndMoney 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable GetExpenseDetail_tbSumCountAndMoney;
        
        /// <summary>
        /// GetExpenseDetail_labSumSendCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label GetExpenseDetail_labSumSendCount;
        
        /// <summary>
        /// GetExpenseDetail_labSumSendMoney 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label GetExpenseDetail_labSumSendMoney;
        
        /// <summary>
        /// GetExpenseDetail_tbExporPageInfo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable GetExpenseDetail_tbExporPageInfo;
        
        /// <summary>
        /// GetExpenseDetail_ExporPageInfoSelect 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Adpost.Common.ExporPage.ExporPageInfoSelect GetExpenseDetail_ExporPageInfoSelect;
    }
}
