//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserBackCenter.TicketsCenter.OrderManage {
    
    
    public partial class OrderDetailInfo {
        
        /// <summary>
        /// OrderDetailInfo_lblFlightName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblFlightName;
        
        /// <summary>
        /// OrderDetailInfo_lblHomeCityId 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblHomeCityId;
        
        /// <summary>
        /// OrderDetailInfo_lblDestCityId 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblDestCityId;
        
        /// <summary>
        /// OrderDetailInfo_lblFlightCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblFlightCode;
        
        /// <summary>
        /// OrderDetailInfo_txtFlightCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtFlightCode;
        
        /// <summary>
        /// OrderDetailInfo_lblLeaveTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblLeaveTime;
        
        /// <summary>
        /// OrderDetailInfo_lblTravellerType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblTravellerType;
        
        /// <summary>
        /// OrderDetailInfo_lblFreightType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblFreightType;
        
        /// <summary>
        /// OrderDetailInfo_lblBackHomeCityId 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBackHomeCityId;
        
        /// <summary>
        /// OrderDetailInfo_lblBackDestCityId 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBackDestCityId;
        
        /// <summary>
        /// OrderDetailInfo_lblBackFlightCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBackFlightCode;
        
        /// <summary>
        /// OrderDetailInfo_txtBackFlightCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtBackFlightCode;
        
        /// <summary>
        /// OrderDetailInfo_lblBackTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBackTime;
        
        /// <summary>
        /// OrderDetailInfo_lblBackTravellerType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBackTravellerType;
        
        /// <summary>
        /// td_PNR 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell td_PNR;
        
        /// <summary>
        /// OrderDetailInfo_lblOrderNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblOrderNo;
        
        /// <summary>
        /// OrderDetailInfo_lblPNR 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblPNR;
        
        /// <summary>
        /// td_PNR1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell td_PNR1;
        
        /// <summary>
        /// OrderDetailInfo_lblUpdatePNR 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblUpdatePNR;
        
        /// <summary>
        /// OrderDetailInfo_txtUpdatePNR 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtUpdatePNR;
        
        /// <summary>
        /// OrderDetailInfo_lblSupplierName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblSupplierName;
        
        /// <summary>
        /// OrderDetailInfo_lblRateType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblRateType;
        
        /// <summary>
        /// OrderDetailInfo_lblLeaveFacePrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblLeaveFacePrice;
        
        /// <summary>
        /// OrderDetailInfo_txtLeaveFacePrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtLeaveFacePrice;
        
        /// <summary>
        /// OrderDetailInfo_lblLeaveDiscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblLeaveDiscount;
        
        /// <summary>
        /// OrderDetailInfo_txtLeaveDiscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtLeaveDiscount;
        
        /// <summary>
        /// ltrLeaveDiscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrLeaveDiscount;
        
        /// <summary>
        /// OrderDetailInfo_lblLeaveTimeLimit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblLeaveTimeLimit;
        
        /// <summary>
        /// OrderDetailInfo_lblLeavePrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblLeavePrice;
        
        /// <summary>
        /// OrderDetailInfo_txtLeavePrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtLeavePrice;
        
        /// <summary>
        /// OrderDetailInfo_lblMaxPCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblMaxPCount;
        
        /// <summary>
        /// OrderDetailInfo_lblLOtherPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblLOtherPrice;
        
        /// <summary>
        /// OrderDetailInfo_txtLOtherPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtLOtherPrice;
        
        /// <summary>
        /// OrderDetailInfo_txtLOtherPrice2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtLOtherPrice2;
        
        /// <summary>
        /// OrderDetailInfo_lblReturnFacePrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblReturnFacePrice;
        
        /// <summary>
        /// OrderDetailInfo_txtReturnFacePrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtReturnFacePrice;
        
        /// <summary>
        /// OrderDetailInfo_lblReturnDiscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblReturnDiscount;
        
        /// <summary>
        /// OrderDetailInfo_txtReturnDiscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtReturnDiscount;
        
        /// <summary>
        /// ltrReturnDiscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrReturnDiscount;
        
        /// <summary>
        /// OrderDetailInfo_lblReturnTimeLimit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblReturnTimeLimit;
        
        /// <summary>
        /// OrderDetailInfo_lblReturnPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblReturnPrice;
        
        /// <summary>
        /// OrderDetailInfo_txtReturnPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtReturnPrice;
        
        /// <summary>
        /// OrderDetailInfo_lblMaxPCount1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblMaxPCount1;
        
        /// <summary>
        /// OrderDetailInfo_lblROtherPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblROtherPrice;
        
        /// <summary>
        /// OrderDetailInfo_txtROtherPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtROtherPrice;
        
        /// <summary>
        /// OrderDetailInfo_txtROtherPrice2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtROtherPrice2;
        
        /// <summary>
        /// OrderDetailInfo_lblContactName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblContactName;
        
        /// <summary>
        /// OrderDetailInfo_lblWorkTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblWorkTime;
        
        /// <summary>
        /// OrderDetailInfo_lblProxyLev 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblProxyLev;
        
        /// <summary>
        /// OrderDetailInfo_lblWebSite 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblWebSite;
        
        /// <summary>
        /// OrderDetailInfo_lblContactTel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblContactTel;
        
        /// <summary>
        /// OrderDetailInfo_lblSuccessRate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblSuccessRate;
        
        /// <summary>
        /// OrderDetailInfo_lblHandleNum 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblHandleNum;
        
        /// <summary>
        /// OrderDetailInfo_lblSubmitNum 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblSubmitNum;
        
        /// <summary>
        /// OrderDetailInfo_lblRefundAvgTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblRefundAvgTime;
        
        /// <summary>
        /// OrderDetailInfo_lblNoRefundAvgTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblNoRefundAvgTime;
        
        /// <summary>
        /// OrderDetailInfo_lblSupplierRemark 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblSupplierRemark;
        
        /// <summary>
        /// OrderDetailInfo_lblTravellerCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblTravellerCount;
        
        /// <summary>
        /// OrderDetailInfo_lblByInsCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblByInsCount;
        
        /// <summary>
        /// OrderDetailInfo_lblBuyItinerary 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBuyItinerary;
        
        /// <summary>
        /// OrderDetailInfo_rptTravellerInfo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater OrderDetailInfo_rptTravellerInfo;
        
        /// <summary>
        /// OrderDetailInfo_lblCustomerCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblCustomerCount;
        
        /// <summary>
        /// OrderDetailInfo_lblPayPrice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblPayPrice;
        
        /// <summary>
        /// td_PayType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell td_PayType;
        
        /// <summary>
        /// td_PayType1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell td_PayType1;
        
        /// <summary>
        /// OrderDetailInfo_lblPayType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblPayType;
        
        /// <summary>
        /// OrderDetailInfo_lblPayPrice1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblPayPrice1;
        
        /// <summary>
        /// OrderDetailInfo_lblRefundCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblRefundCount;
        
        /// <summary>
        /// OrderDetailInfo_txtFee 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox OrderDetailInfo_txtFee;
        
        /// <summary>
        /// OrderDetailInfo_lblRefundprice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblRefundprice;
        
        /// <summary>
        /// OrderDetailInfo_rptOrderLog 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater OrderDetailInfo_rptOrderLog;
        
        /// <summary>
        /// OrderDetailInfo_ltrMQ 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal OrderDetailInfo_ltrMQ;
        
        /// <summary>
        /// OrderDetailInfo_lblBuyerCName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBuyerCName;
        
        /// <summary>
        /// OrderDetailInfo_lblBuyerContactAddress 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBuyerContactAddress;
        
        /// <summary>
        /// OrderDetailInfo_lblBuyerContactName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBuyerContactName;
        
        /// <summary>
        /// OrderDetailInfo_lblBuyerContactMobile 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBuyerContactMobile;
        
        /// <summary>
        /// OrderDetailInfo_lblBuyerRemark 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label OrderDetailInfo_lblBuyerRemark;
        
        /// <summary>
        /// OrderDetailInfo_hidOrderId 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden OrderDetailInfo_hidOrderId;
        
        /// <summary>
        /// OrderDetailInfo_hidOrderState 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden OrderDetailInfo_hidOrderState;
        
        /// <summary>
        /// OrderDetailInfo_hidChangeType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden OrderDetailInfo_hidChangeType;
    }
}
