/*if exists (select * from sysobjects where id = OBJECT_ID('[tbl_SysAdvArea]') and OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [tbl_SysAdvArea]

CREATE TABLE [tbl_SysAdvArea] (
[AreaId] [int]  NOT NULL,
[AreaName] [nvarchar]  (250) NULL,
[CatalogId] [int]  NOT NULL,
[CatalogName] [nvarchar]  (250) NULL,
[AdvCount] [int]  NOT NULL DEFAULT ((0)),
[DisplayType] [tinyint]  NOT NULL DEFAULT ((0)))

ALTER TABLE [tbl_SysAdvArea] WITH NOCHECK ADD  CONSTRAINT [PK_tbl_SysAdvArea] PRIMARY KEY  NONCLUSTERED ( [AreaId] )*/
DELETE [tbl_SysAdvArea]
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 1,'首页广告首页焦点广告翻屏',1,'首页广告',5,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 2,'首页广告公告',1,'首页广告',8,1)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 3,'首页广告爆料区',1,'首页广告',8,1)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 4,'首页广告首页通栏banner1',1,'首页广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 5,'首页广告首页通栏banner2',1,'首页广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 6,'首页广告首页通栏banner3',1,'首页广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 7,'首页广告供求信息下部广告',1,'首页广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 8,'首页广告精品推荐图文',1,'首页广告',5,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 9,'首页广告精品推荐文字',1,'首页广告',10,1)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 10,'首页广告最活跃的企业排名',1,'首页广告',10,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 11,'首页广告优秀企业展示',1,'首页广告',24,6)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType],[IsDisabled]) VALUES ( 12,'首页广告旅游动态文字',1,'首页广告',5,1,'1')
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType],[IsDisabled]) VALUES ( 13,'首页广告旅游动态图文',1,'首页广告',1,3,'1')
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType],[IsDisabled]) VALUES ( 14,'首页广告成功故事文字',1,'首页广告',5,1,'1')
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType],[IsDisabled]) VALUES ( 15,'首页广告成功故事图文',1,'首页广告',1,3,'1')
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 16,'线路频道通栏banner1',2,'线路频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 17,'线路频道精品推荐',2,'线路频道',8,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 18,'线路频道热门景点展示',2,'线路频道',10,7)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 19,'线路频道热闹酒店展示',2,'线路频道',10,7)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 20,'机票频道通栏banner1',3,'机票频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 21,'机票频道通栏banner2',3,'机票频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 22,'景区频道通栏banner1',4,'景区频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 23,'景区频道通栏banner2',4,'景区频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 24,'景区频道本周最热景点图文',4,'景区频道',10,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 25,'景区频道特价门票展示图文',4,'景区频道',8,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 26,'景区频道旗帜广告1',4,'景区频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 27,'景区频道旗帜广告2',4,'景区频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 28,'景区频道最新加入',4,'景区频道',10,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 29,'酒店频道通栏banner1',5,'酒店频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 30,'酒店频道通栏banner2',5,'酒店频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 31,'酒店频道本周最热酒店',5,'酒店频道',10,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 32,'酒店频道特价房展示',5,'酒店频道',8,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 33,'酒店频道旗帜广告1',5,'酒店频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 34,'酒店频道旗帜广告2',5,'酒店频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 35,'酒店频道最新加入',5,'酒店频道',10,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 36,'车队频道精品推荐图文',6,'车队频道',6,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 37,'车队频道旗帜广告1',6,'车队频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 38,'车队频道旗帜广告2',6,'车队频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 39,'车队频道最新加入',6,'车队频道',10,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 40,'旅游用品频道精品推荐图文',7,'旅游用品频道',6,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 41,'旅游用品频道新货上架',7,'旅游用品频道',10,1)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 42,'旅游用品频道旗帜广告1',7,'旅游用品频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 43,'旅游用品频道旗帜广告2',7,'旅游用品频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 44,'旅游用品频道最新加入',7,'旅游用品频道',10,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 45,'购物点频道精品推荐图文',8,'购物点频道',6,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 46,'购物点频道新货上架',8,'购物点频道',10,1)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 47,'购物点频道旗帜广告1',8,'购物点频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 48,'购物点频道旗帜广告2',8,'购物点频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 49,'购物点频道最新加入',8,'购物点频道',10,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 50,'供求信息频道通栏banner',9,'供求信息频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 51,'供求信息频道供求信息文章页图片广告1',9,'供求信息频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 52,'供求信息频道同业之星访谈',9,'供求信息频道',1,3)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 53,'供求信息频道促销广告',9,'供求信息频道',16,1)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 54,'供求信息频道推荐广告',9,'供求信息频道',3,8)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 55,'供求信息频道旗帜广告',9,'供求信息频道',4,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 56,'供求信息频道同业学堂旗帜广告1',9,'供求信息频道',4,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 57,'供求信息频道同业学堂旗帜广告2',9,'供求信息频道',4,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 58,'供求信息频道行业资讯旗帜广告',9,'供求信息频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 59,'MQ主窗体广告',10,'MQ广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 60,'MQ聊天窗口右上广告',10,'MQ广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 61,'MQ聊天窗口右侧广告1',10,'MQ广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 62,'MQ聊天窗口右侧广告2',10,'MQ广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 63,'MQ群窗口右上广告',10,'MQ广告',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 64,'首页广告最新加入企业',1,'首页广告',12,5)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 65,'景区频道景区主题广告',4,'景区频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 66,'供求信息频道文章及列表右侧1',9,'供求信息频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 67,'供求信息频道文章及列表右侧2',9,'供求信息频道',1,2)
INSERT [tbl_SysAdvArea] ([AreaId],[AreaName],[CatalogId],[CatalogName],[AdvCount],[DisplayType]) VALUES ( 68,'供求信息频道最具人气企业推荐',9,'供求信息频道',4,7)

