//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3615 版自动生成。
// 
#pragma warning disable 1591

namespace EyouSoft.BackgroundServices.smsSoap {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmsAPISoap", Namespace="http://tempuri.org/")]
    public partial class SmsAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private APISoapHeader aPISoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback SendOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmsAPI() {
            this.Url = global::EyouSoft.BackgroundServices.Properties.Settings.Default.EyouSoft_BackgroundServices_smsSoap_soap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public APISoapHeader APISoapHeaderValue {
            get {
                return this.aPISoapHeaderValueField;
            }
            set {
                this.aPISoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendCompletedEventHandler SendCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("APISoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResultInfo Send(SendMessageInfo sendMessageInfo) {
            object[] results = this.Invoke("Send", new object[] {
                        sendMessageInfo});
            return ((SendResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void SendAsync(SendMessageInfo sendMessageInfo) {
            this.SendAsync(sendMessageInfo, null);
        }
        
        /// <remarks/>
        public void SendAsync(SendMessageInfo sendMessageInfo, object userState) {
            if ((this.SendOperationCompleted == null)) {
                this.SendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOperationCompleted);
            }
            this.InvokeAsync("Send", new object[] {
                        sendMessageInfo}, this.SendOperationCompleted, userState);
        }
        
        private void OnSendOperationCompleted(object arg) {
            if ((this.SendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCompleted(this, new SendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class APISoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string secretKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendResultInfo {
        
        private bool isSucceedField;
        
        private string errorMessageField;
        
        private decimal countFeeField;
        
        private decimal sendFeeField;
        
        private string tempFeeTakeIdField;
        
        private string sendTotalIdField;
        
        private decimal accountMoneyField;
        
        private int mobileNumberCountField;
        
        private int pHSNumberCountField;
        
        private int successCountField;
        
        private int pHSSuccessCountField;
        
        private int errorCountField;
        
        private int pHSErrorCountField;
        
        private int timeoutCountField;
        
        private int pHSTimeoutCountField;
        
        private int factCountField;
        
        private int pHSFactCountField;
        
        /// <remarks/>
        public bool IsSucceed {
            get {
                return this.isSucceedField;
            }
            set {
                this.isSucceedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public decimal CountFee {
            get {
                return this.countFeeField;
            }
            set {
                this.countFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal SendFee {
            get {
                return this.sendFeeField;
            }
            set {
                this.sendFeeField = value;
            }
        }
        
        /// <remarks/>
        public string TempFeeTakeId {
            get {
                return this.tempFeeTakeIdField;
            }
            set {
                this.tempFeeTakeIdField = value;
            }
        }
        
        /// <remarks/>
        public string SendTotalId {
            get {
                return this.sendTotalIdField;
            }
            set {
                this.sendTotalIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal AccountMoney {
            get {
                return this.accountMoneyField;
            }
            set {
                this.accountMoneyField = value;
            }
        }
        
        /// <remarks/>
        public int MobileNumberCount {
            get {
                return this.mobileNumberCountField;
            }
            set {
                this.mobileNumberCountField = value;
            }
        }
        
        /// <remarks/>
        public int PHSNumberCount {
            get {
                return this.pHSNumberCountField;
            }
            set {
                this.pHSNumberCountField = value;
            }
        }
        
        /// <remarks/>
        public int SuccessCount {
            get {
                return this.successCountField;
            }
            set {
                this.successCountField = value;
            }
        }
        
        /// <remarks/>
        public int PHSSuccessCount {
            get {
                return this.pHSSuccessCountField;
            }
            set {
                this.pHSSuccessCountField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCount {
            get {
                return this.errorCountField;
            }
            set {
                this.errorCountField = value;
            }
        }
        
        /// <remarks/>
        public int PHSErrorCount {
            get {
                return this.pHSErrorCountField;
            }
            set {
                this.pHSErrorCountField = value;
            }
        }
        
        /// <remarks/>
        public int TimeoutCount {
            get {
                return this.timeoutCountField;
            }
            set {
                this.timeoutCountField = value;
            }
        }
        
        /// <remarks/>
        public int PHSTimeoutCount {
            get {
                return this.pHSTimeoutCountField;
            }
            set {
                this.pHSTimeoutCountField = value;
            }
        }
        
        /// <remarks/>
        public int FactCount {
            get {
                return this.factCountField;
            }
            set {
                this.factCountField = value;
            }
        }
        
        /// <remarks/>
        public int PHSFactCount {
            get {
                return this.pHSFactCountField;
            }
            set {
                this.pHSFactCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSChannel {
        
        private int indexField;
        
        private string channelNameField;
        
        private string userNameField;
        
        private string pwField;
        
        private decimal priceOneField;
        
        private bool isLongField;
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelName {
            get {
                return this.channelNameField;
            }
            set {
                this.channelNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Pw {
            get {
                return this.pwField;
            }
            set {
                this.pwField = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceOne {
            get {
                return this.priceOneField;
            }
            set {
                this.priceOneField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLong {
            get {
                return this.isLongField;
            }
            set {
                this.isLongField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AcceptMobileInfo {
        
        private string mobileField;
        
        private bool isEncryptField;
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEncrypt {
            get {
                return this.isEncryptField;
            }
            set {
                this.isEncryptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageInfo {
        
        private string companyIdField;
        
        private string companyNameField;
        
        private string userIdField;
        
        private string userFullNameField;
        
        private int sMSTypeField;
        
        private string sMSContentField;
        
        private System.DateTime sendTimeField;
        
        private AcceptMobileInfo[] mobilesField;
        
        private SendType sendTypeField;
        
        private SMSChannel sendChannelField;
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public int SMSType {
            get {
                return this.sMSTypeField;
            }
            set {
                this.sMSTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SMSContent {
            get {
                return this.sMSContentField;
            }
            set {
                this.sMSContentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        public AcceptMobileInfo[] Mobiles {
            get {
                return this.mobilesField;
            }
            set {
                this.mobilesField = value;
            }
        }
        
        /// <remarks/>
        public SendType SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        public SMSChannel SendChannel {
            get {
                return this.sendChannelField;
            }
            set {
                this.sendChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SendType {
        
        /// <remarks/>
        直接发送,
        
        /// <remarks/>
        定时发送,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SendCompletedEventHandler(object sender, SendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResultInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591